name: Send PDF Report

on:
  schedule:
    - cron: '30 21 * * *'  # Runs every day
  workflow_dispatch:    # Allows manual trigger

jobs:
  send-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex

      - name: Generate Report
        run: |
          echo "# Report Title" > report.md
          echo "This is the content of the report." >> report.md

      - name: Save Report as PDF
        run: |
          pandoc report.md -o Unit Test Status.pdf

      - name: Send Email with PDF Attachment
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Your PDF Report
          body: Please find your PDF report attached.
          to: nkanakam@launchcg.com
          from: nkanakam@launchcg.com
          attachments: Unit Test Status.pdf
