name: Send PDF Report

on:
  schedule:
    - cron: '40 21 * * *'  # Runs every day at midnight
  workflow_dispatch:    # Allows manual trigger

jobs:
  send-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send Email with PDF Attachment
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Your PDF Report
          body: Please find your PDF report attached.
          to: nkanakam@launchcg.com
          from: nkanakam@launchcg.com
          attachments: path/to/your-pdf-file.pdf  # Path to your pre-existing PDF file in the repository
