name: Send PDF Report

on:
  schedule:
    - cron: '0 22 * * *'  # Runs every day at midnight
  workflow_dispatch:    # Allows manual trigger

jobs:
  send-report:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send Email with PDF Attachment
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Your PDF Report
          body: Please find your PDF report attached.
          to: nkanakam@launchcg.com
          from: naveenk932398@gmail.com
          attachments: Unit Test Status.pdf  # Path to your pre-existing PDF file in the repository
